---
# This workflow will install Python dependencies, run tests

name: Create release

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Run CI/CD"]
    types: ["completed"]

jobs:
  create_distributions:
    runs-on: ${{ matrix.os }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: True
      max-parallel: 1
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Create distributions
        run: python build.py
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: distributions
          path: dist
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            This is the latest release and is not production ready.
            Use at your own risk.
          name: latest
          draft: True
          prerelease: True
          files: dist/*.zip
